### ISSUE TITLE
Memory Leak on large number of incoming messages / RMI calls

### ISSUE THREAD

**Issue by AlexanderNeumann** [rwth-acis/las2peer#63]
<p>java <a href="https://www.baeldung.com/java-heap-dump-capture" class="external-link" target="_blank" rel="nofollow noopener">heap</a> <a href="https://heaphero.io/" class="external-link" target="_blank" rel="nofollow noopener">analysis</a> shows that it's most likely due to byte[] or String allocations that aren't being garbage collected. byte[] is connected to decrypted/encrypted messages, while strings could be an indication of an unclosed stream in the ExecutionContext.invoke() method.</p>

<p>Needs further investigation. Once I switched mobsos-success-modeling to <a href="https://github.com/krallin/tini" class="external-link" target="_blank" rel="nofollow noopener">tini</a> to avoid the <a href="https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/" class="external-link" target="_blank" rel="nofollow noopener">zombie reaping problem</a>, I was able to get the java heap and confirm that the app is leaking memory exponentially, but has not reached critical mass in my tests - but that might also be due to not enough time passing for it to have reached the 2GB limit.</p>

<p>Needs further investigation.</p>
<i>[LAS-471] created by mslupczynski</i>

**Comment by pedela** [comment]
@Aran30 Could you please clarify that this issue is different to the one you were tackling the last few days and how? Give it a bit of structure;-)

**Comment by Aran30** [comment]
As far as I'm concerned, I believe that this was indeed the issue we fixed with the new release.
When analysing the heap for leaks in the old version, the mentioned hashtable caused a lot of allocated byte[] objects to not be garbage collected (After a crash, there were 3492 undeleted byte[] objects, which occupied approx. 3,6 Gb of the heap). 
The new version only had about 100Kb of byte[] objects hanging around after 10000 messages were exchanged (No crash occured so I stopped the node after about 3 hours of exchanging messages). 

For the same amount of messages, there also were only 860Kb of String allocations left.  

I'd say that this issue can be closed once this week has passed and no crash occured?
